

# Configuration BlockParty - Simple
# Liste des builds à cloner pour l'animation

builds:
  build1:
    name: "Rubiks Cube"
    color_blocks:
      - "RED_CONCRETE"
      - "BLUE_CONCRETE"
      - "GREEN_CONCRETE"
      - "YELLOW_CONCRETE"

  build2:
    name: "JSPBRO"
    color_blocks:
      - "ORANGE_CONCRETE"
      - "PURPLE_CONCRETE"
      - "PINK_CONCRETE"
      - "CYAN_CONCRETE"

  build3:
    name: "JSPBRO3"
    color_blocks:
      - "LIME_CONCRETE"
      - "LIGHT_BLUE_CONCRETE"
      - "WHITE_CONCRETE"
      - "BLACK_CONCRETE"

# Paramètres de timing
game:
  animation_duration: 2.0  # secondes d'animation de clonage rapide
  clone_speed: 0.2        # intervalle entre chaque clone (en secondes)
  time_to_choose: 8.0       # temps pour aller sur la bonne couleur
  time_between_rounds: 3  # temps entre les rounds

  # Taille commune de tous les builds (carré)
  build_size: 30  # Tous les builds font 30x30 blocs
  # Coordonnées où cloner le build choisi
  clone_destination:
    world: "event"
    x: 0
    y: 64
    z: 0
