

# Configuration BlockParty - Simple
# Liste des builds à cloner pour l'animation

builds:
  build1:
    world: "world"
    name: "Rubiks Cube"
    source_corner1: { x: 100, y: 64, z: 100 }
    source_corner2: { x: 120, y: 64, z: 120 }
    color_blocks:
      - "RED_CONCRETE"
      - "BLUE_CONCRETE"
      - "GREEN_CONCRETE"
      - "YELLOW_CONCRETE"

  build2:
    world: "world"
    name: "JSPBRO"
    source_corner1: { x: 200, y: 64, z: 200 }
    source_corner2: { x: 220, y: 64, z: 220 }
    color_blocks:
      - "ORANGE_CONCRETE"
      - "PURPLE_CONCRETE"
      - "PINK_CONCRETE"
      - "CYAN_CONCRETE"

  build3:
    world: "world"
    name: "JSPBRO3"
    source_corner1: { x: 300, y: 64, z: 300 }
    source_corner2: { x: 320, y: 64, z: 320 }
    color_blocks:
      - "LIME_CONCRETE"
      - "LIGHT_BLUE_CONCRETE"
      - "WHITE_CONCRETE"
      - "BLACK_CONCRETE"

# Paramètres de timing
game:
  animation_duration: 2.0  # secondes d'animation de clonage rapide
  clone_speed: 0.2        # intervalle entre chaque clone (en secondes)
  time_to_choose: 8       # temps pour aller sur la bonne couleur
  time_between_rounds: 3  # temps entre les rounds
