name: BlockParty
version: 1.0
main: org.blockPartyGame.BlockPartyEvent
api-version: 1.21
depend: [SimpleEventManager]
commands:
  blockparty:
    description: Reload BlockParty config
    usage: /blockparty reload
    permission: blockparty.admin

permissions:
  blockparty.admin:
    description: Autorise l'utilisation de /blockparty reload
    default: op